default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["MYSQL_USER"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  host: <%= ENV["MYSQL_HOST"] %>

development:
  <<: *default
  database: <%= ENV["MYSQL_DATABASE"] %>
  
test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: <%= ENV['HEROKU_DB_DATABASE_NAME'] %>
  host: <%= ENV['HEROKU_DB_HOST'] %>
  username: <%= ENV['HEROKU_DB_USERNAME'] %>
  password: <%= ENV['HEROKU_DB_PASSWORD'] %>
  url: <%= ENV['JAWSDB_URL'] %>