default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["MYSQL_USER"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  host: <%= ENV["MYSQL_HOST"] %>
  port: 3306
  timeout: 5000
  reconnect: true
  connect_timeout: 10
  read_timeout: 10
  write_timeout: 10
  # Rails 7.0での安定性向上
  prepared_statements: false
  variables:
    sql_mode: STRICT_TRANS_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO

development:
  <<: *default
  database: <%= ENV["MYSQL_DATABASE"] %>

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: <%= ENV['HEROKU_DB_DATABASE_NAME'] %>
  host: <%= ENV['HEROKU_DB_HOST'] %>
  username: <%= ENV['HEROKU_DB_USERNAME'] %>
  password: <%= ENV['HEROKU_DB_PASSWORD'] %>
  url: <%= ENV['JAWSDB_URL'] %>